using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace CyberKnet.Foscam
{
    public enum FoscamResponseType
    {
        RESPONSE_REQUEST_PORT = 50000,
        RESPONSE_REQUSET_LOGIN = 50001,
        RESPONSE_REQUEST_LOGOUT = 50002,
        RESPONSE_REQUEST_RELEASE = 50003,
        RESPONSE_REQUEST_AUDIO = 50004,
        RESPONSE_REQUEST_TALK = 50005,
        RESPONSE_REQUEST_CGI = 50006,
        RESPONSE_REQUEST_SNAP = 50007,
        RESPONSE_REQUEST_LOGIN_PRODUCT_INFO = 50008,
        RESPONSE_REQUEST_LOGIN_MSG_INIT_INFO = 50009,
        RESPONSE_REQUEST_OPEN_VIDEO = 50010,
        RESPONSE_REQUEST_CLOSE_VIDEO = 50011,
        RESPONSE_REQUEST_OPEN_VIDEO_SUCCESS = 50012,
        RESPONSE_REQUEST_SELECT_FILE = 50013,
        RESPONSE_REQUEST_GET_FILE_SIZE = 50014,
        RESPONSE_REQUEST_FIRMWARE_UPGRADE_FAKE_CGI_RESULT = 50016,
        RESPONSE_REQUEST_FIRMWARE_UPGRADE_MSG = 50017,
        RESPONSE_REQUEST_SEARCH_DEV_IP_AND_PORT = 50018,

        RESPONSE_REQUEST_IMPORT_CONFIG_FILE = 50019,
        RESPONSE_REQUEST_SAVE_RECORD_PATH = 50020,
        RESPONSE_REQUEST_GET_RECORD_PATH = 50021,
        RESPONSE_REQUEST_OPEN_RECORD_PATH = 50022,
        RESPONSE_REQUEST_RECORD = 50023,
        RESPONSE_REQUEST_SELECT_RECORD_PATH = 50024,
        RESPONSE_REQUEST_SD_MANAGER = 50025,
        RESPONSE_REQUEST_LOGIN_AGAIN = 50026
}
}
